### ISSUE TITLE
Graph including "docker username" during dev

### ISSUE THREAD

**Issue by langdon** [projectatomic/nulecule#11] opened 2015-03-31 23:19 UTC
While I am developing my sub-apps for my overall-app, I want to be able to use the "name that will appear in the registry" without having done a push to the registry yet in the graph.

e.g.  
  "graph": [ "my-user/redis-app", "my-app" ]

but, on disk, it is graph/my-user-redis-app? or graph/my-user.redis-app? or graph/my-user/redis-app ? because I haven't pushed it to the registry yet.

**Comment by aweiteka** [comment] 2015-04-01 01:56
Maybe `docker tag` would support this workflow? Do a local docker build, tag it, then it will be named the right thing but be local on the box.

**Comment by langdon** [comment] 2015-04-01 14:53
Arguably. I guess when I was trying it last night (fooling around with Hubot), I didn't even have a dockerfile yet. I was just trying to get the directory structure created and my Atomicfiles created. After that, I would go in to do the individual Dockerfiles. So, even with docker tag, for me, the default order of operations was wrong.

**Comment by vpavlin** [comment] 2015-04-16 18:59
This has changed now - you have either the extrnal source `source: docker://...` or a component of your Nulecule app..so I thing this is basically fixed in 1.0.0 " by design"

**Closed as completed** 2015-04-16 19:17 UTC
