### ISSUE TITLE
Exception on atomic stop

### ISSUE THREAD

**Issue by ggallen** [projectatomic/nulecule#157] opened 2015-08-26 13:19 UTC
When trying to to stop the helloapache sample program I get the following exception:

```
[root@atomic atomic-test]# atomic stop projectatomic/helloapache
Traceback (most recent call last):
  File "/usr/bin/atomic", line 248, in <module>
    sys.exit(args.func())
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 381, in stop
    self.display(cmd)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 719, in display
    subprocess.check_call("/usr/bin/echo \"" + cmd  + "\"", env=self.cmd_env, shell=True)
  File "/usr/lib/python2.7/site-packages/Atomic/atomic.py", line 453, in cmd_env
    if self.args.opt1:
AttributeError: 'Namespace' object has no attribute 'opt1'
[root@atomic atomic-test]# 
```

**Comment by goern** [comment] 2015-08-26 13:45
This seems to be a Atomic App issue?!

**Comment by vpavlin** [comment] 2015-08-26 13:47
It's either `atomic` issue or labels in Atomic App Dockerfile are messed up. Hard to guess..

**Comment by dustymabe** [comment] 2015-08-28 16:29
This is the issue https://github.com/projectatomic/atomic/issues/137

**Comment by dustymabe** [comment] 2015-08-28 18:33
This issue can be closed as it is not a bug in nulecule.

**Comment by goern** [comment] 2015-08-28 19:13
thx dusty!

**Closed as completed by goern** 2015-08-28 19:13 UTC
Labels: bug
